#!/usr/bin/env bash
# Fill credentials.env. The file is mode 600 and is never committed.
set -euo pipefail

cd "$(dirname "$0")"

if [[ ! -f credentials.env ]]; then
  cp credentials.env.example credentials.env
  chmod 600 credentials.env
fi

declare -A CFG

load() {
  local line key value
  unset CFG
  declare -gA CFG
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[A-Z0-9_]+= ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    CFG["$key"]="$value"
  done < credentials.env
}

save() {
  umask 077
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp" <<EOF
# Generated by configure.sh. Do not commit.
SERVICE_IMAGE=${CFG[SERVICE_IMAGE]}
HOST_PORT=${CFG[HOST_PORT]}
NILO_CONSOLE_USERNAME=${CFG[NILO_CONSOLE_USERNAME]}
NILO_CONSOLE_PASSWORD=${CFG[NILO_CONSOLE_PASSWORD]}
NILO_INGEST_API_KEY=${CFG[NILO_INGEST_API_KEY]}
MONGO_USER=${CFG[MONGO_USER]}
MONGO_PASSWORD=${CFG[MONGO_PASSWORD]}
MINIO_ROOT_USER=${CFG[MINIO_ROOT_USER]}
MINIO_ROOT_PASSWORD=${CFG[MINIO_ROOT_PASSWORD]}
EOF
  mv "$tmp" credentials.env
  chmod 600 credentials.env
  echo "Wrote credentials.env (mode 600)."
  echo "First container start copies these values into the archive volume."
  echo "After that, change them in the web console, then run ./deploy.sh only if MongoDB or MinIO must be recreated."
}

is_safe() {
  [[ "$1" =~ ^[A-Za-z0-9._-]{8,128}$ ]]
}

require_secret() {
  local key="$1"
  local value="${CFG[$key]}"
  case "$value" in
    ""|CHANGE_ME|nilo-dev-key|nilo-secret|change-me)
      echo "$key is still a placeholder." >&2
      return 1
      ;;
  esac
  if ! is_safe "$value"; then
    echo "$key must be 8-128 characters: letters, digits, dot, underscore, hyphen." >&2
    return 1
  fi
}

prompt_value() {
  local key="$1"
  local label="$2"
  local secret="${3:-}"
  local current="${CFG[$key]:-}"
  local shown="$current"
  local input
  if [[ "$secret" == secret ]]; then
    if [[ -n "$current" && "$current" != CHANGE_ME ]]; then
      shown="(already set)"
    else
      shown="(empty)"
    fi
    read -r -s -p "$label $shown: " input
    echo
  else
    read -r -p "$label [$shown]: " input
  fi
  if [[ -n "$input" ]]; then
    CFG["$key"]="$input"
  fi
}

test_connections() {
  local port="${CFG[HOST_PORT]:-8088}"
  local failed=0
  if curl -fsS --max-time 3 "http://127.0.0.1:${port}/v1/health" >/dev/null; then
    echo "archive API ok"
  else
    echo "archive API did not answer on port ${port}" >&2
    failed=1
  fi
  if curl -fsS --max-time 3 -o /dev/null "http://127.0.0.1:${port}/console"; then
    echo "console ok"
  else
    echo "console did not answer on port ${port}" >&2
    failed=1
  fi
  if curl -fsS --max-time 3 "http://127.0.0.1:9000/minio/health/live" >/dev/null; then
    echo "MinIO ok"
  else
    echo "MinIO did not answer on 127.0.0.1:9000" >&2
    failed=1
  fi
  if docker compose --env-file credentials.env exec -T mongo \
    mongosh --quiet \
    --username "${CFG[MONGO_USER]}" \
    --password "${CFG[MONGO_PASSWORD]}" \
    --authenticationDatabase admin \
    --eval "db.adminCommand('ping')" >/dev/null; then
    echo "MongoDB ok"
  else
    echo "MongoDB did not answer. Start the stack with ./deploy.sh first." >&2
    failed=1
  fi
  return "$failed"
}

load

if [[ ! -t 0 ]]; then
  echo "configure.sh needs a terminal. Copy credentials.env.example and edit it." >&2
  exit 1
fi

while true; do
  cat <<EOF

NILO datalake — credentials
  1) Console username          ${CFG[NILO_CONSOLE_USERNAME]:-}
  2) Console password
  3) Ingest API key
  4) MongoDB user              ${CFG[MONGO_USER]:-}
  5) MongoDB password
  6) MinIO user                ${CFG[MINIO_ROOT_USER]:-}
  7) MinIO password
  8) Published port            ${CFG[HOST_PORT]:-8088}
  9) Image                     ${CFG[SERVICE_IMAGE]:-}
  s) Save
  t) Test connections (stack must already be up)
  q) Quit
EOF
  read -r -p "> " choice
  case "$choice" in
    1) prompt_value NILO_CONSOLE_USERNAME "Console username" ;;
    2) prompt_value NILO_CONSOLE_PASSWORD "Console password" secret ;;
    3) prompt_value NILO_INGEST_API_KEY "Ingest API key" secret ;;
    4) prompt_value MONGO_USER "MongoDB user" ;;
    5) prompt_value MONGO_PASSWORD "MongoDB password" secret ;;
    6) prompt_value MINIO_ROOT_USER "MinIO user" ;;
    7) prompt_value MINIO_ROOT_PASSWORD "MinIO password" secret ;;
    8) prompt_value HOST_PORT "Host port for the console and the API" ;;
    9) prompt_value SERVICE_IMAGE "Image" ;;
    s)
      if ! require_secret NILO_CONSOLE_PASSWORD \
        || ! require_secret NILO_INGEST_API_KEY \
        || ! require_secret MONGO_PASSWORD \
        || ! require_secret MINIO_ROOT_PASSWORD; then
        continue
      fi
      if [[ ! "${CFG[HOST_PORT]}" =~ ^[0-9]+$ ]]; then
        echo "HOST_PORT must be a number." >&2
        continue
      fi
      save
      ;;
    t) test_connections || true ;;
    q) exit 0 ;;
    *) echo "Unknown option." ;;
  esac
done
