#!/usr/bin/env bash
# Fill credentials.env. The file is mode 600 and is never committed.
set -euo pipefail

cd "$(dirname "$0")"

if ! docker info >/dev/null 2>&1 && [[ -S /var/run/docker.sock && "${NILO_DOCKER_REEXEC:-}" != 1 ]]; then
  if ! id -nG "$USER" | tr ' ' '\n' | grep -qx docker; then
    echo "Adding ${USER} to the docker group..."
    sudo usermod -aG docker "$USER"
  fi
  if id -nG "$USER" | tr ' ' '\n' | grep -qx docker && command -v sg >/dev/null 2>&1; then
    echo "This login was opened before the docker group applied. Continuing with that group..."
    quoted_args="$(printf '%q ' "$@")"
    exec sg docker -c "NILO_DOCKER_REEXEC=1 exec $(printf '%q' "$0") ${quoted_args}"
  fi
fi

if [[ ! -f credentials.env ]]; then
  cp credentials.env.example credentials.env
  chmod 600 credentials.env
fi

declare -A CFG

load() {
  local line key value
  unset CFG
  declare -gA CFG
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[A-Z0-9_]+= ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    CFG["$key"]="$value"
  done < credentials.env
}

save() {
  umask 077
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp" <<EOF
# Generated by configure.sh. Do not commit.
SERVICE_IMAGE=${CFG[SERVICE_IMAGE]}
HOST_PORT=${CFG[HOST_PORT]}
NILO_CONSOLE_USERNAME=${CFG[NILO_CONSOLE_USERNAME]}
NILO_CONSOLE_PASSWORD=${CFG[NILO_CONSOLE_PASSWORD]}
NILO_INGEST_API_KEY=${CFG[NILO_INGEST_API_KEY]}
MINIO_ROOT_USER=${CFG[MINIO_ROOT_USER]}
MINIO_ROOT_PASSWORD=${CFG[MINIO_ROOT_PASSWORD]}
EOF
  mv "$tmp" credentials.env
  chmod 600 credentials.env
  echo "Wrote credentials.env (mode 600)."
  echo "The first datalake start copies these values into the archive volume."
  echo "After that, change them in the web console."
}

is_safe() {
  [[ "$1" =~ ^[A-Za-z0-9._-]{8,128}$ ]]
}

require_secret() {
  local key="$1"
  local value="${CFG[$key]}"
  case "$value" in
    ""|CHANGE_ME|nilo-dev-key|nilo-secret|change-me)
      echo "$key is still a placeholder." >&2
      return 1
      ;;
  esac
  if ! is_safe "$value"; then
    echo "$key must be 8-128 characters: letters, digits, dot, underscore, hyphen." >&2
    return 1
  fi
}

prompt_value() {
  local key="$1"
  local label="$2"
  local secret="${3:-}"
  local current="${CFG[$key]:-}"
  local shown="$current"
  local input
  if [[ "$secret" == secret ]]; then
    if [[ -n "$current" && "$current" != CHANGE_ME ]]; then
      shown="(already set)"
    else
      shown="(empty)"
    fi
    read -r -s -p "$label $shown: " input
    echo
  else
    read -r -p "$label [$shown]: " input
  fi
  if [[ -n "$input" ]]; then
    CFG["$key"]="$input"
  fi
}

explain_console_down() {
  local port="$1"
  echo "Nothing is accepting connections on 127.0.0.1:${port}." >&2
  echo "Container status:" >&2
  docker compose --env-file credentials.env ps >&2 || true
  echo "Last datalake logs:" >&2
  docker compose --env-file credentials.env logs --tail 40 datalake >&2 || true
}

console_page_up() {
  local base="$1"
  local page_file="$2"
  local code
  code="$(curl -s -L --max-time 5 -o "$page_file" -w '%{http_code}' "${base}/console" 2>/dev/null || true)"
  [[ "$code" == 200 ]] && grep -q "NILO archive console" "$page_file"
}

check_web() {
  local port="${CFG[HOST_PORT]:-8088}"
  local base="http://127.0.0.1:${port}"
  local user="${CFG[NILO_CONSOLE_USERNAME]:-}"
  local pass="${CFG[NILO_CONSOLE_PASSWORD]:-}"
  local page_file login_file settings_file jar code
  page_file="$(mktemp)"
  login_file="$(mktemp)"
  settings_file="$(mktemp)"
  jar="$(mktemp)"
  echo "Checking ${base}/console ..."
  if ! console_page_up "$base" "$page_file"; then
    echo "The console is not running. Starting the archive and the web page..."
    if ! ./deploy.sh; then
      echo "The console did not start." >&2
      explain_console_down "$port"
      rm -f "$page_file" "$login_file" "$settings_file" "$jar"
      return 1
    fi
  fi
  if ! console_page_up "$base" "$page_file"; then
    echo "The console page is still not up." >&2
    explain_console_down "$port"
    rm -f "$page_file" "$login_file" "$settings_file" "$jar"
    return 1
  fi
  echo "Console page is up."
  if [[ -z "$user" || -z "$pass" || "$pass" == CHANGE_ME ]]; then
    echo "Set the console username and password before testing login." >&2
    rm -f "$page_file" "$login_file" "$settings_file" "$jar"
    return 1
  fi
  code="$(curl -s --max-time 5 -o "$login_file" -w '%{http_code}' -c "$jar" \
    -H 'content-type: application/json' \
    -d "{\"username\":\"${user}\",\"password\":\"${pass}\"}" \
    "${base}/console/api/login" || true)"
  if [[ "$code" != 200 ]]; then
    echo "Login failed (HTTP ${code:-none}). The page answers, but ${user} was rejected." >&2
    echo "If the password was changed in the web console, credentials.env no longer matches the running service." >&2
    rm -f "$page_file" "$login_file" "$settings_file" "$jar"
    return 1
  fi
  code="$(curl -s --max-time 5 -o "$settings_file" -w '%{http_code}' -b "$jar" \
    "${base}/console/api/settings" || true)"
  rm -f "$page_file" "$login_file" "$settings_file" "$jar"
  if [[ "$code" != 200 ]]; then
    echo "Login succeeded but the session could not open settings (HTTP ${code:-none})." >&2
    return 1
  fi
  echo "Login succeeded for ${user}. The console is operational."
}

load

if [[ ! -t 0 ]]; then
  echo "configure.sh needs a terminal. Copy credentials.env.example and edit it." >&2
  exit 1
fi

while true; do
  cat <<EOF

NILO datalake — credentials
  1) Console username          ${CFG[NILO_CONSOLE_USERNAME]:-}
  2) Console password
  3) Ingest API key
  4) MinIO user                ${CFG[MINIO_ROOT_USER]:-}
  5) MinIO password
  6) Published port            ${CFG[HOST_PORT]:-8088}
  7) Image                     ${CFG[SERVICE_IMAGE]:-}
  s) Save
  m) Install MinIO if it is not already running
  w) Start the console if needed, then test the page and login
  q) Quit
EOF
  read -r -p "> " choice
  case "$choice" in
    1) prompt_value NILO_CONSOLE_USERNAME "Console username" ;;
    2) prompt_value NILO_CONSOLE_PASSWORD "Console password" secret ;;
    3) prompt_value NILO_INGEST_API_KEY "Ingest API key" secret ;;
    4) prompt_value MINIO_ROOT_USER "MinIO user" ;;
    5) prompt_value MINIO_ROOT_PASSWORD "MinIO password" secret ;;
    6) prompt_value HOST_PORT "Host port for the console and the API" ;;
    7) prompt_value SERVICE_IMAGE "Image" ;;
    s)
      if ! require_secret NILO_CONSOLE_PASSWORD \
        || ! require_secret NILO_INGEST_API_KEY \
        || ! require_secret MINIO_ROOT_PASSWORD; then
        continue
      fi
      if [[ ! "${CFG[HOST_PORT]}" =~ ^[0-9]+$ ]]; then
        echo "HOST_PORT must be a number." >&2
        continue
      fi
      save
      if curl -fsS --max-time 3 http://127.0.0.1:9000/minio/health/live >/dev/null 2>&1; then
        echo "MinIO is already running."
      else
        echo "MinIO is not running. Installing it..."
        ./deploy.sh --ensure-minio
      fi
      ;;
    m)
      if ! require_secret MINIO_ROOT_PASSWORD; then
        continue
      fi
      save
      ./deploy.sh --ensure-minio || true
      ;;
    w) check_web || true ;;
    q) exit 0 ;;
    *) echo "Unknown option." ;;
  esac
done
